name: Deploy SFMC Queries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy SQL to SFMC Query Activities
        uses: volvo-cars/sfmc-query-activity@v1
        with:
          config-file: './sfmc-queries.yml'
          sfmc-client-id: ${{ secrets.SFMC_CLIENT_ID }}
          sfmc-client-secret: ${{ secrets.SFMC_CLIENT_SECRET }}
          sfmc-account-id: ${{ secrets.SFMC_ACCOUNT_ID }}
