name: Deploy SFMC Queries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy SQL to SFMC Query Activities
        uses: volvo-cars/sfmc-query-activity@v1
        with:
          config-file: './sfmc-queries.yml'
          sfmc-client-id: ${{ secrets.sphgyo8xgkx4zt16b2p1n906 }}
          sfmc-client-secret: ${{ secrets.877oRnzNuNx4pIdsqiSqSpVd }}
          sfmc-account-id: ${{ secrets.7328812 }}
